### ISSUE TITLE
NoSuchMethodError: MySafeDelegator.compareAndSwapLong

### ISSUE THREAD

**Issue by yaud** [serkan-ozal/mysafe#2]
Looks like MySafeDelegator doesn't implement all methods from Unsafe:

java.lang.NoSuchMethodError: tr.com.serkanozal.mysafe.impl.MySafeDelegator.compareAndSwapLong(Lsun/misc/Unsafe;Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z
	at io.netty.util.internal.UnsafeAtomicReferenceFieldUpdater.compareAndSet(UnsafeAtomicReferenceFieldUpdater.java:39)
	at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.getAndSet(AtomicReferenceFieldUpdater.java:191)
	at io.netty.util.internal.MpscLinkedQueueTailRef.getAndSetTailRef(MpscLinkedQueueTailRef.java:52)
	at io.netty.util.internal.MpscLinkedQueue.offer(MpscLinkedQueue.java:129)
	at io.netty.util.internal.MpscLinkedQueue.add(MpscLinkedQueue.java:221)
...

**Comment by serkan-ozal** [comment]
@yaud sorry for delay. the issue has been fixed by version `2.1`
